pipelines:
  - name: sample_pipeline
    steps:
      - name: {{ .Values.sample_step_1.name }}
        type: {{ .Values.sample_step_1.type }}
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
      - name: sample_step_2
        type: Bash
        configuration:
          runtime:
            type: host
          inputSteps:
            - name: {{ .Values.sample_step_1.name }}
        execution:
          onExecute:
            - printenv
 
